project: {{cookiecutter.project_name}}
version: 0.1.0

defaults:
  machine_config:
    type: ec2
    mem: 16Gib
    vcpu: 4
  env_vars:
    project: {{cookiecutter.project_name}}

environments:
  develop:
    pipelines:
      - example_pipeline:
          env_vars:
            env: develop
          network_settings:
            api_hostname: dev-api.aineko.dev
            port: 8000

      - large_tx_1

  production:
    pipelines:
      - large_tx_all:
          machine_config:
            type: ec2
            mem: 32Gib
            vcpu: 8


pipelines:
  example_pipeline:
    source: ./conf/pipeline.yml
    machine_config:
      type: ec2
      mem: 8Gib
      vcpu: 2

  large_tx_1:
    source: ./conf/pipeline_runs.yml
    name: large_tx_1

  large_tx_all:
    source: ./conf/pipeline_runs.yml
